services:

  # App\Command\CreateUser:
  #         class: App\Command\CreateUserCommand
  #         tags:
  #             - { name: 'console.command' }

  App\Command\:
      resource: '../../src/Command/'
      tags:
              - { name: 'console.command' }
      autowire: true





  