ewz_recaptcha:
    # For reCAPTCHA v2, use the following test keys. You will always get No CAPTCHA and all verification requests will pass.
    # https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha-v2-what-should-i-do
    public_key: '%env(EWZ_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(EWZ_RECAPTCHA_SECRET)%'
    # Not needed as "%kernel.default_locale%" is the default value for the locale key
    locale_key:  "%kernel.default_locale%"
    locale_from_request: true
    api_host: recaptcha.net
