# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

# twig:
#     form_themes:
#         - '@FOSCKEditor/Form/ckeditor_widget.html.twig'


fos_ck_editor:
    base_path: "/assets/plugins/ckeditor"
    js_path:   "/assets/plugins/ckeditor/ckeditor.js"
    jquery_path: "/assets/plugins/ckeditor/adapters/jquery.js"
    jquery: true
    configs:
        my_config:
            toolbar: basic