# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    enable_authenticator_manager: true

    password_hashers:
        # Use native password hasher, which auto-selects and migrates the best
        # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    encoders:
        # FOS\UserBundle\Model\UserInterface: bcrypt
        # FOS\UserBundle\Model\UserInterface: auto
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPERADMIN:  [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        app_user_provider:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
                provider: app_user_provider
                # csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                enable_csrf: true
            logout:
                path: /logout
                target: /login
            switch_user: { role: ROLE_SUPERADMIN }
            # anonymous: true
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/comment/, role: ROLE_MODERATOR }
        - { path: ^/admin/, role: ROLE_SUPERADMIN }
