# twig:
#     default_path: '%kernel.project_dir%/templates'

# when@test:
#     twig:
#         strict_variables: true


twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'Widget/form.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
