appControllers:
    resource: ../../src/Controller/
    type: annotation

controllers:
    resource: ../../lib/AppBundle/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
