#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

logout:
    path: /logout

login:
    path: /login

login_check:
    path: /login_check

# resetting_request:
#     path: /resetting/request
#     controller: AppBundle\Controller\ResettingController::request

# resetting_send_email:
#     path: /resetting/send-email
#     controller: AppBundle\Controller\ResettingController::sendEmail

# resetting_check_email:
#     path: /check-email
#     controller: AppBundle\Controller\ResettingController::checkEmail

