# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    router.request_context.scheme: https
    router.request_context.host: www.world-parliament.org

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $smsMessage: '%env(SMS_MESSAGE)%'
            $smsContentType: '%env(SMS_CONTENT_TYPE)%'
            $smsAuth: '%env(SMS_AUTHORIZATION)%'
            $smsSender: '%env(SMS_SENDER)%'
            $smsApiUrl: '%env(API_URL)%'
            $smsAccID: '%env(SMS_ACCOUNTID)%'
            $fb_token: '%env(FB_PAGE_TOKEN)%'
            $fb_site: '%env(FB_PAGE_ID)%'
            $fb_app: '%env(FB_APP)%'
            $fb_secret: '%env(FB_SECRET)%'
            $lkin_access_token: '%env(LKIN_ACCESS_TOKEN)%'
            $lkin_organization: '%env(LKIN_ORGANIZATION)%'
            $lkinClientId: '%env(LKIN_CLIENT_ID)%'
            $lkinClientSecret: '%env(LKIN_CLIENT_SECRET)%'
            $lkinRefreshToken: '%env(LKIN_REFRESH_TOKEN)%'
            $senderEmail: '%env(SENDER_EMAIL)%'
            $projectDir: '%kernel.project_dir%'
            $apiKey: '%env(GEMINI_API_KEY)%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\:
        resource: '../src/Service/'
        autowire: true
    App\Command\:
        resource: '../src/Command/'
        autowire: true

    App\Util\:
        resource: '../src/Util/'
        autowire: true

    App\Service\Mailer:
        class: App\Service\Mailer
        arguments:
            $senderEmail: '%env(SENDER_EMAIL)%'
        autowire: true

    # App\Twig\PageExtension:
    #     public: false
    #     autowire: true
    #     tags:
    #         - { name: twig.extension }

    # App\Twig\WidgetExtension:
    #     public: false
    #     tags:
    #         - { name: twig.extension }

    # App\Twig\TimeDiffExtension:
    #     tags:
    #         - { name: twig.extension }

    # App\Twig\TextExtension:
    #     tags:
    #         - { name: twig.extension }

    App\Twig\:
        resource: '../src/Twig/'
        autowire: true
        tags:
            - { name: twig.extension }

    App\Annotation\Page:
        public: true

    App\Menu\MenuBuilder:
        arguments: ["@knp_menu.factory", '@security.authorization_checker']
        # arguments: ['@security.authorization_checker']
        autowire: true
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    App\EventSubscriber\LoginSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # App\Form\DelegationForm:
    #     public: false
    #     autowire: true

    # App\Form\InitiativeUserForm:
    #     public: false
    #     autowire: true

    App\Form\:
        resource: '../src/Form/'
        autowire: true

    App\Security\InitiativeVoter:
        public: false
        arguments:
            - '@security.access.decision_manager'
        tags:
            - { name: security.voter }

    # Symfony\Component\Mailer\MailerInterface:
